# Generated by Django 6.0.6 on 2026-07-14 12:09

import cloudinary_storage.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_casefile_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='gazettement_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('GAZETTED', 'Gazetted')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='casefile',
            name='requires_gazettement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_here', to='tracker.location'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='reference_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='handled_by',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Gazettement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gazette_notice_number', models.CharField(max_length=100)),
                ('gazette_date', models.DateField()),
                ('volume_issue', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('logged_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gazettements', to='tracker.casefile')),
            ],
            options={
                'ordering': ['-gazette_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tracker.casefile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_notification_id', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_read', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
